### ISSUE TITLE
Spelling error in GitHub description

### ISSUE THREAD

**Issue by RichardLitt** [yesvods/react-constant#2]
Might be worth fixing `global`? :) 

```
Fuck off constants.js and golobal constants in react/flux/redux/wateva.
```

**Comment by yesvods** [comment]
Thx~

**Comment by RichardLitt** [comment]
Np. Just checked - it's in the package.json too. https://github.com/yesvods/react-constant/blob/master/package.json#L4

**Comment by yesvods** [comment]
Pull Request is welcome 😜 @RichardLitt
